### PR TITLE
Remove byebug and swap it with pry-byebug

### PR DESCRIPTION
**Pull request by cintamani**
byebug has a very similar interface as gdb, but byebug does not use the powerful Pry REPL.
binding.pry uses Pry, but lacks some of the byebug features.
[pry-byebug](https://github.com/deivid-rodriguez/pry-byebug) brings some capabilities byebug to binding.pry, so using that, will give you the most debugging powers.

Credits: https://docs.gitlab.com/ee/development/pry_debugging.html#byebug-vs-bindingpry

### CODE REVIEW

**Comment by cintamani** [comment]
Sure :) I'll add more details

**Comment by cintamani** [comment]
@Cruikshanks I was actually thinking that we might get all-the-power if we use https://github.com/deivid-rodriguez/pry-byebug WDYT?

**Comment by Cruikshanks** [comment]
Go for it @cintamani !

**Comment by cintamani** [comment]
@Cruikshanks ready for review :)

**Pull request merged**
