### PR TITLE
Add transient addresses has_one associations to TransientRegistration

### PR DESCRIPTION
**Pull request by cintamani**
With this little trick, we don't have to worry any more about stuff like "Can add or replace an address" as we have the ability to manipulate the transient addresses separate.
It does also make more sense logically and makes the form nested attribute implementation much easier.

The code using this is part of a bigger PR that will land later.

### CODE REVIEW

**Comment by cintamani** [comment]
@irisfaraway allow for `accept_nested_parameters` to work. The difference is that it returns an object like ActiveRecordRelation were you can chain rails methods while the implementation of `#find_address_by_type` will return a `TransientAddress` object directly

**Comment by cintamani** [comment]
Also, you are able to assign a `transient_site_address`. You can do stuff like `transient_registration.build_transient_site_address` directly, and it will replace the one in the `transient addresses` array, so we don't need to do stuff like https://github.com/DEFRA/waste-exemptions-engine/blob/master/app/forms/concerns/waste_exemptions_engine/can_add_or_replace_an_address.rb#L8

Basically, allow to use rails to do rails stuff XD

**Comment by irisfaraway** [comment]
@cintamani Would it make sense to replace the existing methods with something like this then? (For registrations and their addresses as well).

I'm just wondering if having two very similar methods for different purposes (`transient_registration.transient_site_address` and `transient_registration.site_address`) could cause confusion.

**Comment by cintamani** [comment]
@irisfaraway I hope to get rid of these: https://github.com/DEFRA/waste-exemptions-engine/blob/e3f715f5bf6e4753cf243651ca6d909fa1b77fe7/app/models/concerns/waste_exemptions_engine/can_have_registration_attributes.rb#L26-L36 when I have done the other forms too :)

**Comment by irisfaraway** [comment]
@cintamani What happens if we remove the `transient_` bits from the names of the new relationships? Can we just do an immediate replace of the old methods as part of this PR?

I think they are used a fair amount in the back office as well so it'd save a lot of find-and-replacing.

**Comment by cintamani** [comment]
@irisfaraway I could do that, but I find it very confusing that they don't include the `transient_` bit. They confuse me as I always expect a `Address` object and I get a `TransientAddress` one, so I prefer to deal with the find and replace :D

**Comment by irisfaraway** [comment]
@cintamani Ahh, I prefer not having `transient` as I think it clutters up the code and assume that the sub-relations of a `transient_registration` will always be `transient_` things anyway. So maybe we need @Cruikshanks for the deciding vote!

**Comment by irisfaraway** [comment]
Also then we can call `.site_address` on an object without worrying whether it is a `Registration` or `TransientRegistration`, which is useful for a lot of things

**Comment by cintamani** [comment]
Yep found them! Will `:alias` :)

**Comment by cintamani** [comment]
As per face-to-face discussion, I am going to merge this and open a different PR for adding :alias and removing the implementation of the other methods

**Pull request merged**
